language: python
sudo: false
python:
  - "3.5"

install:
  - gem install sass
  - npm install
  - grunt sass
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - pip install dist/*.whl

script:
  # - cd example1 && make html && cd - # Requires msmbuilder
  - cd example2 && make html && cd -

deploy:
  provider: s3
  bucket: "sphinx-modern-theme"
  skip_cleanup: true
  region: "us-west-1"
  access_key_id:
    secure: "fL/dz61uh4wfhIB4aR0VPDgu87Ev7IfBVOGaUuu4/DCwT4MM8Bw2NaKtjgDBqucpZpGTF/KLeXT+h2on1o6tSa7JOcJilnVzvDjWpykC0ZJSaUv0AD6UaU0a37YhazHqgDXHiTDFfOLbxNn5Lz73UX/tDYoarZ5KA1aSD7ZXnVCgIzDc5DIHwBlkadxXEiNKy80Z4ZVgII3hUaIMtGvbL3Y/5M/9IGt6QENpM6HpFjwfiOLx0pxe2KeWiav9/UUMcd4XeJBrbcRYZTu76HNbpfbF58wXOJeyncsFoAd/pmDwVzGfusd8hsDcnoyv4lI7itHfejRybEYPnLadIZ1ZEdGe2ALDIdNmnS6qvhvxpcXfiXA4nS+gDCEz1J4FtjLCaslv3MiKQz9ZMOEa9u+tKDAMlpvkxpEaKM3RXq9Gvq7IQScyAu+2q5s2Oj2dKWYggop231bz0Xucxu3q8gjainDDHpmqcwxFOGj+xOmVKY8zeFffFrgot1HK/d+cBJhX5SPWx40vt/HBQPSgj6PvDtagFKUaYfwv5eoJLxiGH4Uhy2hu06GTIACebSztNn5lwgw+JVxfyqUzrCi5RuxB1BGtvWuhhyQKinumn2fjEsi6QhEfwV6pFdcD5ba9fPk2QKQPnqWoxn4+ladpYtsQPMUOqM7kKn/bR7r80V7Qa7c="
  secret_access_key:
    secure: "s03dwejvWfL9ziMWNT+bwMAQ/HJjDYBs9lNr1oLS5Jnk2UAQ20AVm9OUF2CoYyNhj/Oiy/KYadNcgbQatbJumzBVNz2usNjJSmaNIeG/v1SUdEZtLn9rfWy5x9wZeu3ymemR313aTVaX/LexVobCSm2UlRnUmKi5CNiHtprZUIW+Fd/qKK3fIaudM+suGVlScAPbjw1bGQo7b5H4+fe+x2yKHLh89rZUQi7LCyMaIw+VNUQ3TnpE4cK7/VfGxnBEVeA7Uqo4mqd//I2PgGuAUh/od6iNiUWZgD7SD0RiBQjOMui2po1QzEU0HdV0VNa5Xy3Yni9VxXMAMC2z14VyhlHW2UJhKhYn/tz/udr0KcLiJr8zPg5v7cF1N7aMGaSzZd7mELnkS0YTJzmJ8sm3kxFLU2SyrwCMzmhOlaVMKDiZuneWntmkWxNxshA2TU9LspV4FQzRmdwvb/X+HBL/NkuGuGfVzeoskOqnT1Q1mg72QDFdittpO4Si4ogJ6cwKMBgpZrCU1wD+E5A5EBGjuK+gJ6Kobgd0pYuIIRCgVGwelzkxPLYNwfSFxtPwh5OAn4mYo796G9d9xoyyqYyTdYqQEZRCvhIrKWArGme39F2xeRAx10AfckZsycbIf4KEkASo3X9EFUbKcFGimzoS3pqo9rgnN+4HXa1K+bgj5ek="
