language: python
sudo: false
python:
  - "3.5"

install:
  - gem install sass
  - npm install
  - grunt sass
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - pip install dist/*.whl

  # Stuff for examples
  - pip install numpy scipy scikit-learn # wheels
  # Special version of numpydoc with patch to attempt to reduce output
  - pip install https://github.com/mpharrigan/numpydoc/archive/v0.6.2.zip

script:
  - cd $TRAVIS_BUILD_DIR/example-example && make html && mv build/html ../dist/example-example
  # Too much output:
  # - cd $TRAVIS_BUILD_DIR/example-sklearn > /dev/null && make html && mv _build/html/stable ../dist/example-sklearn
  - cd $TRAVIS_BUILD_DIR/example-msmbuilder && make html && mv _build/html ../dist/example-msmbuilder
  - cd $TRAVIS_BUILD_DIR/docs && make html && mv _build/html ../dist/docs
  - cd $TRAVIS_BUILD_DIR && python handle-versioning.py

deploy:
  - provider: s3
    bucket: "sphinx-modern-theme"
    skip_cleanup: true
    region: "us-west-1"
    access_key_id:
      secure: "K8qy/BwdwCB2ohiPmbZi9kC23Y0+FAxyymwkKmSqm4BWaNTbL8FUrmEyBYFh9x+RURaxkbDFOmM7mS1AMLWDFwSvIsqlDA4QtFiIg26UCDKk34boNlUmnDFmRQfDHjtkBC7VhYeEmx92sivIRwcFaO0+00q+oAusoAKtHuDlyTNjjFfda4BleQewu7CJG/HeBBueT0HAKZboe0Od32pYWNnaC5wyXJGGARffkuhRna6LfaD4Axab351FmSmIksN7URi9DpYmfx/9fT2OdU1WMPjqHGkh9xV9cvvO9YtqgMJhPhTz+9gRjMnzm2RyJhoCxGvRrcoq0s4oc4EPrVUX+NlaSo+RBR4OgRb4YywMSDf3vWTjxu7jzNVV9QvXBg+6A4n3G+lhVufmTB5q81eOfIeBr2ZTAbXfLPRC+Ga0531LLSzZOBJTcNAkS3GgqPPgIb9UfWuQgNYyT/ROCAK3OubxbZrY3oZ3kSyy6sZXpQhwJOoedVubGDSL344HYaKzivMKRxLuvKJR0NKOwQnLdM/rLtRCCTvOJNbJAiYdjfVXwxZb8+cVwF75KmmSrbh+Piu6cRrflK3bVXxHbotjQEUTCywu8ck9kwEKotyeyuuM0Z5dEyF4l3VN3ya8AOIMYh22ti92iLQhqVSnsOqWT4MPyjBimiabDZNcS+7BYC8="
    secret_access_key:
      secure: "lj6gaLXifjuQVnTHFSsGTyf4u3hhdV4hjTb3dWJg4cWf1S9DVITJE3QWrJAqKRk0OjtZ5Z3205Gpf57pjl0Alj7/H0MhiZ40ifbdOrV6RG069CXw8NKfek/KcySGItUvEQcO+pPIqtx5f73PDGPYuTd2v1jlHGtuhLMvKHvwYIC9ZArvREHIL5r5A1XyPYmFlqN9EnQ1YI+nBkLTYto26zZeCwml0Z6UR+5xpXggVE9EPJgkCPggxXEu8eqT4G6OQZ00xKzohkFhNAdVNIlq7Ftwp0cNdeDToJyGwkdrwFfQajmlen223QmkZCMxAjQaC6eCI0oSaXplYt/GYjyP8GhuNBP7v/d/wObfJBSChASNtaJo7RxR3WmwAmI9P76zyB43g0NWPGYwa8RX+niq2UYoH+cSBxAYiL3anMZlEyS0MJCgupAz7fOVmthb3lapzP3jOOlm1BRHrZgofCiUZZVWwaFZHb5hP2MfuqLSarqbZM2VKP6bkfxaVz75hnnoSOVwa4eAcfuBBuOHxEhhLtddsU5k3mX7zV5usvF5NfXbmC5J2aX4Q/BVjo9mFYFTIrTaWP38w3S0CqKan8HlH2QAQ7gHZkwJw2yb+NuqYECN0v21JbYAGUBTkp+uH1I25y8qrMezOeCO7qRhegX5rPis1lh2cRBmtayEfWHypy4="
    local_dir: dist
    on:
      tags: true
  - provider: pypi
    user: mpharrigan
    password:
      secure: "jjlxXcDlZ67TEoEVFOSwK4JVwfFZklx7wFrKvkjnnaZBjns6lwFcLftkZWlSrrlBh/CsjBSkuXqf4t13fwtVnpHN5olKoGLxXsHRS8NPicOoJElAgTrVbwkWMTLjzGEDV+Bxeai0jZR9MfjfdpoQRgRS8huXpr1lQLXdcVtDA4z5in7+RA8HZ99VzDhaeRkVsWvPN+fjcCJzEIISR/oC1J0+cb/NIZynnWCBqLTdVRCeE07RFKAloUhZZu2vlacfw54N2SrkGiI/H4Z4uqjpAc7KUABDtEgxIYQYxPT4Zqhd2+qmfBbfDhCWi15bCCRhkznT7lMqFsyzUaORCF24n9hLM2v/UH6QnZqarkMJp9UjjSk/Vfx/KGMHVWMGdh2XgLVciHsobv3n3tl4l6A+s6PxH9+zIJ+SCT5JtHi4rKsyG4vJRFUwlWwmeGww7oieQPT/kx3ogyFnGnxnT1Q92JDZfFyrkIfLY7DyXGQafyM9EaZiB2PDyhsDPgbk+kRkj5t6rYxsTBtL6PqgpE208raKNwwaL3XKoRCrMqkkrWyX+W7cPTmW4asB0G72KNehO/JLilQByD3qj0YM97wwdSk/d6R1etYhKlLBh8IyssXvax8DQgPZq0c3DWKE4Finfai9+xl2zOJAmEpgaD6XQhy+U8hEk6N0owwTmihkSHQ="
    on:
      tags: true
      all_branches: true
    distributions: "bdist_wheel"
    skip_cleanup: true
